version: "3.7"

services:
  runner:
    image: feedehc/github-docker-runner
    container_name: runner-self-hosted
    privileged: true
    environment:
      RUNNER_NAME: "runner-esp32"
      RUNNER_REPOSITORY_URL: ${RUNNER_REPOSITORY_URL}
      RUNNER_ORGANIZATION_URL: ${RUNNER_ORGANIZATION_URL}
      GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sockz

    devices:
      - '/dev/ttyUSB0:/dev/ttyUSB0'
